version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'exampleDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - 'mysqldata:/var/lib/mysql'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/redis/data'

volumes:
  mysqldata:
  redisdata: